version: 2.1

orbs:
  ci: geos-esm/circleci-tools@1

workflows:
  build-test:
    jobs:
      # Build GEOSgcm
      - ci/build:
          name: build-GEOSgcm-on-<< matrix.compiler >>
          context:
            - docker-hub-creds
          matrix:
            parameters:
              compiler: [gfortran, ifort]
          baselibs_version: v7.0.0
          repo: GEOSgcm
          checkout_fixture: true
          mepodevelop: true
          checkout_mapl3_release_branch: true
          persist_workspace: false # Needs to be true to run fv3/gcm experiment, costs extra
