version: 2
jobs:
  build:
    docker:
      - image: gmao/geos-build-env:6.0.4
    working_directory: /root/project
    steps:
      - run:
          name: "GEOSgcm_GridComp branch"
          command: echo ${CIRCLE_BRANCH}
      - checkout
      - run:
          name: "Checkout GEOSgcm fixture and update GEOSgcm_GridComp branch"
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}
            git clone git@github.com:GEOS-ESM/GEOSgcm.git
            cd GEOSgcm
            mepo init
            mepo clone
            mepo develop GEOSgcm_GridComp GEOSgcm_App
            mepo checkout-if-exists ${CIRCLE_BRANCH}
            mepo status
      - run:
          name: "Fix linker flags"
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/GEOSgcm
            sed -i -e '$aset(CMAKE_EXE_LINKER_FLAGS    "${CMAKE_EXE_LINKER_FLAGS}    -Wl,--unresolved-symbols=ignore-all")' ./@cmake/GNU.cmake
      - run:
          name: "CMake"
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/GEOSgcm
            mkdir build
            cd build
            cmake .. -DBASEDIR=$BASEDIR/Linux -DCMAKE_Fortran_COMPILER=gfortran -DCMAKE_BUILD_TYPE=Debug
      - run:
          name: "Build"
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/GEOSgcm/build
            make -j2 install
