"""GF2020 convection parameterization interface"""

import numpy as np
from gt4py.cartesian.gtscript import i32

from ndsl import QuantityFactory, StencilFactory, orchestrate
from ndsl.constants import X_DIM, Y_DIM, Z_DIM, Z_INTERFACE_DIM
from ndsl.dsl.typing import Float, FloatField, FloatFieldIJ, Int
from pyMoist.convective_parameterization.GF2020.GF2020_internal_variables import (
    outputs,
    temporaries,
    namelist_constants,
)

from pyMoist.convective_parameterization.GF2020.pre_cumulus_param import (
    zero_outputs,
    setup_driver,
)
from pyMoist.convective_parameterization.GF2020.cumulus_parameterization_wrapper import (
    cumulus_parameterization,
)

# used only during construction
from pyMoist.convective_parameterization.GF2020.GF2020_flags import GF2020_flags


class GEOS5:
    def __init__(
        self,
        stencil_factory: StencilFactory,
        quantity_factory: QuantityFactory,
        GF2020_flags: GF2020_flags,
    ):
        self.stencil_factory = stencil_factory
        self.quantity_factory = quantity_factory
        self.GEOS5_flags = GF2020_flags

        self.outputs = outputs(self, quantity_factory)
        self.temporaries = temporaries(self, quantity_factory)
        self.namelist_constants = namelist_constants(self, GF2020_flags.MAXIENS)

        orchestrate(obj=self, config=stencil_factory.config.dace_config)
        self._zero_outputs = self.stencil_factory.from_dims_halo(
            func=zero_outputs,
            compute_dims=[X_DIM, Y_DIM, Z_DIM],
        )
        self._setup_driver = self.stencil_factory.from_dims_halo(
            func=setup_driver,
            compute_dims=[X_DIM, Y_DIM, Z_DIM],
            externals={
                "USE_SCALE_DEP": GF2020_flags.USE_SCALE_DEP,
                "N_TRACERS": GF2020_flags.N_TRACERS,
            },
        )

        self.cumulus_parameterization = cumulus_parameterization(
            self, stencil_factory, quantity_factory, GF2020_flags
        )

    def __call__(
        self,
        lons,
        lats,
        dt_moist,
        ple,
        plo,
        zle,
        zlo,
        pk,
        mass,
        kh,
        t,
        th,
        q,
        u,
        v,
        w,
        buoyancy,
        qlcn,
        qicn,
        qlls,
        qils,
        cnpcprate,
        cnv_mf0,
        cnv_prc3,
        cnv_mfd,
        cnv_dqcdt,
        entlam,
        cnv_mfc,
        cnv_updf,
        cnv_cvw,
        cnv_qc,
        clcn,
        clls,
        qv_dyn,
        ple_dyn,
        u_dyn,
        v_dyn,
        t_dyn,
        radsw,
        radlw,
        dqdt_bl,
        dtdt_bl,
        land_fraction,
        area,
        t2m,
        q2m,
        ta,
        qa,
        sh,
        evap,
        phis,
        kpblin,
        cnvfrc,
        srftype,
        stochastic_sig,
        sigma_deep,
        sigma_mid,
        dqdt_gf,
        dtdt_gf,
        dudt_gf,
        dvdt_gf,
        cnv_topp_dp,
        cnv_topp_md,
        cnv_topp_sh,
        mupdp,
        mupsh,
        mupmd,
        mdndp,
        mfdp,
        mfsh,
        mfmd,
        errdp,
        errsh,
        errmd,
        wqt_dc,
        aa0,
        aa1,
        aa2,
        aa3,
        aa1_bl,
        aa1_cin,
        tau_bl,
        tau_ec,
        dtdt_dyn,
        dqvdt_dyn,
        revsu,
        entr3d,
        entr_dp,
        entr_md,
        entr_sh,
        prfil,
        tpwi,
        tpwi_star,
        lightn_dens,
        cnv_tr,
    ):

        self._zero_outputs(
            wqt_dc,
            self.outputs.cnv_mfc,
            cnv_mf0,
            cnv_prc3,
            cnv_mfd,
            cnv_dqcdt,
            cnv_updf,
            cnv_cvw,
            cnv_qc,
            entlam,
            cnpcprate,
            lightn_dens,
            revsu,
            prfil,
            dqdt_gf,
            dtdt_gf,
            dudt_gf,
            dvdt_gf,
            sigma_deep,
            sigma_mid,
            mupdp,
            mdndp,
            mupsh,
            mupmd,
            mfdp,
            mfsh,
            mfmd,
            errdp,
            errsh,
            errmd,
            aa0,
            aa1,
            aa2,
            aa3,
            aa1_bl,
            aa1_cin,
            tau_bl,
            tau_ec,
        )

        self._setup_driver(
            # inputs
            dt_moist,
            t2m,
            evap,
            sh,
            ple,  # +1 vertical level
            t,
            q,
            u,
            v,
            w,
            phis,
            land_fraction,
            area,
            zle,  # +1 vertical level
            plo,
            zlo,
            mass,
            kh,
            buoyancy,
            kpblin,
            ple_dyn,  # Z+1
            self.temporaries.zle_dyn,  # Z+1
            t_dyn,
            qv_dyn,
            u_dyn,
            v_dyn,
            dtdt_dyn,
            dqvdt_dyn,
            dtdt_bl,
            dqdt_bl,
            radsw,
            radlw,
            cnv_tr,
            lons,
            lats,
            # outputs passed to driver but not handed back to the rest of the model
            self.temporaries.temp2m,
            self.temporaries.temp_old,
            self.temporaries.temp_new,
            self.temporaries.temp_new_bl,
            self.temporaries.temp_new_adv,
            self.temporaries.qv_old,
            self.temporaries.qv_new,
            self.temporaries.qv_new_bl,
            self.temporaries.qv_new_adv,
            self.temporaries.ocean_fraction,
            self.temporaries.dx2d,
            self.temporaries.pbl_top_level,
            # forcings
            self.temporaries.buoyancy_excess,
            self.temporaries.gsf_t,
            self.temporaries.gsf_q,
            self.temporaries.sgsf_t,
            self.temporaries.sgsf_q,
            self.temporaries.advf_t,
            # end forcings
            self.temporaries.temp_old,
            self.temporaries.temp_new_adv,
            self.temporaries.zws,
            self.temporaries.last_ierr,
            self.temporaries.fixout_qv,
            self.temporaries.conprr,
            self.temporaries.out_chem_1_deep,
            self.temporaries.out_chem_2_deep,
            self.temporaries.out_chem_1_mid,
            self.temporaries.out_chem_2_mid,
            self.temporaries.out_chem_1_shal,
            self.temporaries.out_chem_2_shal,
            self.temporaries.topo_height_no_neg,
            self.temporaries.lons_degrees,
            self.temporaries.lats_degrees,
            self.temporaries.revsu_gf,
            self.temporaries.prfil_gf,
            self.temporaries.temp_tendqv,
            self.temporaries.outt_deep,
            self.temporaries.outt_mid,
            self.temporaries.outt_shal,
            self.temporaries.outu_deep,
            self.temporaries.outu_mid,
            self.temporaries.outu_shal,
            self.temporaries.outv_deep,
            self.temporaries.outv_mid,
            self.temporaries.outv_shal,
            self.temporaries.outq_deep,
            self.temporaries.outq_mid,
            self.temporaries.outq_shal,
            self.temporaries.outqc_deep,
            self.temporaries.outqc_mid,
            self.temporaries.outqc_shal,
            self.temporaries.outnice_deep,
            self.temporaries.outnice_mid,
            self.temporaries.outnice_shal,
            self.temporaries.outnliq_deep,
            self.temporaries.outnliq_mid,
            self.temporaries.outnliq_shal,
            self.temporaries.outbuoy_deep,
            self.temporaries.outbuoy_mid,
            self.temporaries.outbuoy_shal,
            self.temporaries.omega,
            self.temporaries.ccn,
            self.temporaries.sensible_heat_sfc_flux,
            self.temporaries.latent_heat_sfc_flux,
            # outputs needed after the driver
            self.temporaries.dz,
            self.temporaries.air_density,
            self.temporaries.temp,
            self.temporaries.pres,
            self.temporaries.rvap,
            self.temporaries.up,
            self.temporaries.vp,
            self.temporaries.wp,
            self.temporaries.zt,
            self.temporaries.zm,
            self.temporaries.dm,
            self.temporaries.khloc,
            self.temporaries.curr_rvap,
            # outputs passed to the driver, then back to the rest of the model
            self.outputs.lightn_dens,  # also goes to driver
            self.outputs.cnv_tr,  # also goes to driver
            # outputs passed back to the rest of the model
            self.outputs.entr3d,
        )

        cumulus_parameterization(
            self.temporaries.temp2m,
            self.temporaries.temp_old,
            self.temporaries.temp_new,
            self.temporaries.temp_new_bl,
            self.temporaries.temp_new_adv,
            self.temporaries.qv_old,
            self.temporaries.qv_new,
            self.temporaries.qv_new_bl,
            self.temporaries.qv_new_adv,
            self.temporaries.ocean_fraction,
            self.temporaries.dx2d,
            self.temporaries.pbl_top_level,
            # forcings
            self.temporaries.buoyancy_excess,
            self.temporaries.gsf_t,
            self.temporaries.gsf_q,
            self.temporaries.sgsf_t,
            self.temporaries.sgsf_q,
            self.temporaries.advf_t,
            # end forcings
            self.temporaries.zws,
            self.temporaries.last_ierr,
            self.temporaries.fixout_qv,
            self.temporaries.conprr,
            self.temporaries.out_chem_1_deep,
            self.temporaries.out_chem_2_deep,
            self.temporaries.out_chem_1_mid,
            self.temporaries.out_chem_2_mid,
            self.temporaries.out_chem_1_shal,
            self.temporaries.out_chem_2_shal,
            self.temporaries.topo_height_no_neg,
            self.temporaries.lons_degrees,
            self.temporaries.lats_degrees,
            self.temporaries.revsu_gf,
            self.temporaries.prfil_gf,
            self.temporaries.temp_tendqv,
            self.temporaries.outt_deep,
            self.temporaries.outt_mid,
            self.temporaries.outt_shal,
            self.temporaries.outu_deep,
            self.temporaries.outu_mid,
            self.temporaries.outu_shal,
            self.temporaries.outv_deep,
            self.temporaries.outv_mid,
            self.temporaries.outv_shal,
            self.temporaries.outq_deep,
            self.temporaries.outq_mid,
            self.temporaries.outq_shal,
            self.temporaries.outqc_deep,
            self.temporaries.outqc_mid,
            self.temporaries.outqc_shal,
            self.temporaries.outnice_deep,
            self.temporaries.outnice_mid,
            self.temporaries.outnice_shal,
            self.temporaries.outnliq_deep,
            self.temporaries.outnliq_mid,
            self.temporaries.outnliq_shal,
            self.temporaries.outbuoy_deep,
            self.temporaries.outbuoy_mid,
            self.temporaries.outbuoy_shal,
            self.temporaries.omega,
            self.temporaries.ccn,
            self.temporaries.sensible_heat_sfc_flux,
            self.temporaries.latent_heat_sfc_flux,
            # outputs passed back to the rest of the model
            self.outputs.lightn_dens,
            self.outputs.cnv_tr,
        )
